# Generated by Django 5.1.2 on 2024-10-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_dimposts_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimposts',
            name='userId',
            field=models.IntegerField(),
        ),
    ]
