.PHONY: up down build test logs clean

up:
	docker-compose up -d

down:
	docker-compose down

build:
	docker-compose build

test:
	docker-compose run --rm web pytest

logs:
	docker-compose logs -f

clean:
	docker-compose down
	docker volume prune